packages:
    - packages/gui
    - packages/branding
    - packages/vm
    - packages/blocks
    - packages/render
    - packages/render-fonts
    - packages/paint

ignoredBuiltDependencies:
    - core-js

onlyBuiltDependencies:
    - chromedriver
    - electron
    - electron-winstaller
    - es5-ext
    - esbuild

shamefullyHoist: true
